// Transactional tables only. Keep static seed tables intact.
export const TRANSACTIONAL_TABLES: string[] = [
  'sales_orders',
  'order_items',
  'order_item_modifiers',
  'payments',
  'refunds',
  'register_sessions',
  'cash_movements',
  'denomination_counts',
  'inventory_movements',
  'kitchen_tickets',
  'kitchen_ticket_items',
  'table_reservations',
  'deliveries',
  'addresses',
  'discount_usages',
  'audit_logs',
  'compliance_invoices',
  'invoice_compliance',
  'compliance_events',
  'report_executions',
  'outbox_events',
  'inbox_events',
];
